
version: '3.8'

services:

  db: 
    image: postgres:13
    container_name: db
    environment:
      DB_USER: tf-db
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: tf-db.czjiom3rtt6e.us-east-1.rds.amazonaws.com
    ports:
      - "5432:5432"
    volumes:
      - /postgres:/var/lib/postgresql/data
